services:
  # Postgres
  bee-guardian-server:
    container_name: bee-guardian-server
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app

  postgres:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}

  redis:
    image: redis
    ports:
      - "6379:6379"
